GRANT USAGE ON SCHEMA notes TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA notes TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA notes TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA notes TO "apps";