CREATE
OR REPLACE FUNCTION function_grants_permission_to_apps_user(schema_ text)
  RETURNS void AS
$BODY$
BEGIN
EXECUTE format('GRANT USAGE ON SCHEMA %I TO "apps"', schema_);
EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA %I TO "apps"', schema_);
EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA %I TO "apps"', schema_);
EXECUTE format('GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA %I TO "apps"', schema_);
EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO "apps"',
        schema_);
EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT EXECUTE ON FUNCTIONS TO "apps"', schema_);
EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA %I GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "apps"', schema_);

RETURN;
END;
$BODY$
LANGUAGE plpgsql;