//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Contient la moyenne de l'�l�ve, de la structure et l'appr�ciation
 *                 pour une discipline et un (ou plusieurs) enseignant(s)
 *             
 * 
 * <p>Java class for Acquis complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Acquis">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appreciation" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine600" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="discipline-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="enseignant-refs" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="element-programme-refs" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *       &lt;attribute name="moyenne-eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}MoyenneAlphanumerique" />
 *       &lt;attribute name="moyenne-structure" type="{urn:fr:edu:scolarite:lsun:bilans:import}MoyenneAlphanumerique" />
 *       &lt;attribute name="eleve-non-note" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="structure-non-notee" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="positionnement" type="{urn:fr:edu:scolarite:lsun:bilans:import}PositionnementAcquis" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Acquis", propOrder = {
    "appreciation"
})
public class Acquis {

    protected String appreciation;
    @XmlAttribute(name = "discipline-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object disciplineRef;
    @XmlAttribute(name = "enseignant-refs", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> enseignantRefs;
    @XmlAttribute(name = "element-programme-refs", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> elementProgrammeRefs;
    @XmlAttribute(name = "moyenne-eleve")
    protected String moyenneEleve;
    @XmlAttribute(name = "moyenne-structure")
    protected String moyenneStructure;
    @XmlAttribute(name = "eleve-non-note")
    protected Boolean eleveNonNote;
    @XmlAttribute(name = "structure-non-notee")
    protected Boolean structureNonNotee;
    @XmlAttribute(name = "positionnement")
    protected BigInteger positionnement;

    /**
     * Gets the value of the appreciation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppreciation() {
        return appreciation;
    }

    /**
     * Sets the value of the appreciation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppreciation(String value) {
        this.appreciation = value;
    }

    /**
     * Gets the value of the disciplineRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDisciplineRef() {
        return disciplineRef;
    }

    /**
     * Sets the value of the disciplineRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDisciplineRef(Object value) {
        this.disciplineRef = value;
    }

    /**
     * Gets the value of the enseignantRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enseignantRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnseignantRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getEnseignantRefs() {
        if (enseignantRefs == null) {
            enseignantRefs = new ArrayList<Object>();
        }
        return this.enseignantRefs;
    }

    /**
     * Gets the value of the elementProgrammeRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the elementProgrammeRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getElementProgrammeRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getElementProgrammeRefs() {
        if (elementProgrammeRefs == null) {
            elementProgrammeRefs = new ArrayList<Object>();
        }
        return this.elementProgrammeRefs;
    }

    /**
     * Gets the value of the moyenneEleve property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoyenneEleve() {
        return moyenneEleve;
    }

    /**
     * Sets the value of the moyenneEleve property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoyenneEleve(String value) {
        this.moyenneEleve = value;
    }

    /**
     * Gets the value of the moyenneStructure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMoyenneStructure() {
        return moyenneStructure;
    }

    /**
     * Sets the value of the moyenneStructure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMoyenneStructure(String value) {
        this.moyenneStructure = value;
    }

    /**
     * Gets the value of the eleveNonNote property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEleveNonNote() {
        return eleveNonNote;
    }

    /**
     * Sets the value of the eleveNonNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEleveNonNote(Boolean value) {
        this.eleveNonNote = value;
    }

    /**
     * Gets the value of the structureNonNotee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStructureNonNotee() {
        return structureNonNotee;
    }

    /**
     * Sets the value of the structureNonNotee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStructureNonNotee(Boolean value) {
        this.structureNonNotee = value;
    }

    /**
     * Gets the value of the positionnement property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionnement() {
        return positionnement;
    }

    /**
     * Sets the value of the positionnement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionnement(BigInteger value) {
        this.positionnement = value;
    }

}
