/*
 * Copyright (c) Région Hauts-de-France, Département de la Seine-et-Marne, CGI, 2016.
 *     This file is part of OPEN ENT NG. OPEN ENT NG is a versatile ENT Project based on the JVM and ENT Core Project.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as
 *   published by the Free Software Foundation (version 3 of the License).
 *   For the sake of explanation, any module that communicate over native
 *   Web protocols, such as HTTP, with OPEN ENT NG is outside the scope of this
 *   license and could be license under its own terms. This is merely considered
 *   normal use of OPEN ENT NG, and does not fall under the heading of "covered work".
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Adresse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Adresse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ligne1" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50" />
 *       &lt;attribute name="ligne2" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50" />
 *       &lt;attribute name="ligne3" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50" />
 *       &lt;attribute name="ligne4" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50" />
 *       &lt;attribute name="code-postal" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine10" />
 *       &lt;attribute name="commune" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine100" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Adresse")
public class Adresse {

    @XmlAttribute(name = "ligne1", required = true)
    protected String ligne1;
    @XmlAttribute(name = "ligne2")
    protected String ligne2;
    @XmlAttribute(name = "ligne3")
    protected String ligne3;
    @XmlAttribute(name = "ligne4")
    protected String ligne4;
    @XmlAttribute(name = "code-postal", required = true)
    protected String codePostal;
    @XmlAttribute(name = "commune", required = true)
    protected String commune;

    public Adresse(){}
    public Adresse(String adress,String codePostal, String commune){
        //this.ligne1 = adress;
        this.cutAdressSetLigne(adress);
        this.codePostal=codePostal;
        this.commune=commune;
    }
    /**
     * Gets the value of the ligne1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLigne1() {
        return ligne1;
    }

    /**
     * Sets the value of the ligne1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLigne1(String value) {
        this.ligne1 = value;
    }

    /**
     * Gets the value of the ligne2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLigne2() {
        return ligne2;
    }

    /**
     * Sets the value of the ligne2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLigne2(String value) {
        this.ligne2 = value;
    }

    /**
     * Gets the value of the ligne3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLigne3() {
        return ligne3;
    }

    /**
     * Sets the value of the ligne3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLigne3(String value) {
        this.ligne3 = value;
    }

    /**
     * Gets the value of the ligne4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLigne4() {
        return ligne4;
    }

    /**
     * Sets the value of the ligne4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLigne4(String value) {
        this.ligne4 = value;
    }

    /**
     * Gets the value of the codePostal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodePostal() {
        return codePostal;
    }

    /**
     * Sets the value of the codePostal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodePostal(String value) {
       // if(value!=null) {
            this.codePostal = value;
       /* }else{
            this.codePostal = "00000";
        }*/
    }

    /**
     * Gets the value of the commune property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommune() {
        return commune;
    }

    /**
     * Sets the value of the commune property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommune(String value) {
        this.commune = value;
    }

    /**
     * Set ligne1, lign2, ligne3, ligne4 in function the length of adress
     * @param adress
     */
    public void cutAdressSetLigne(String adress){

        if(adress.length() > 50) {
            String[] tabAdress = adress.split(" ");
            for (int i = 0; i < tabAdress.length; i++) {

                if (ligne1 == null ){
                    ligne1 = tabAdress[i];
                }else if((ligne1.length() + tabAdress[i].length())+1 <= 50) {
                    ligne1 = ligne1 +" "+ tabAdress[i];
                } else if(ligne2 == null) {
                    if (tabAdress[i].length() <= 50) {
                        ligne2 = " " + tabAdress[i];
                    } else {
                        int endIndexString = tabAdress[i].length();
                        ligne2 = " " + tabAdress[i].substring(0, 50);
                        ligne3 = tabAdress[i].substring(51, endIndexString);
                    }
                }else if ((ligne2.length()+tabAdress[i].length())+1 <= 50 ) {
                    ligne2 = ligne2 +" "+ tabAdress[i];
                }else if (ligne3 == null){
                    ligne3 = " "+tabAdress[i];
                }else if((ligne3.length() + tabAdress[i].length())+1 <= 50 ){
                    ligne3 = ligne3 +" "+ tabAdress[i];
                }else if(ligne4 == null) {
                    ligne4 = " "+ tabAdress[i];
                }else if((ligne4.length() + tabAdress[i].length())+1 <= 50) {
                    ligne4 = ligne4 + " " + tabAdress[i];
                }
            }
            this.setLigne1(ligne1);
            if(ligne2!=null){
                this.setLigne2(ligne2);
            }
            if(ligne3!=null){
                this.setLigne3(ligne3);
            }
            if(ligne4!=null){
                this.setLigne4(ligne4);
            }

        }else{
            this.setLigne1(adress);
        }
    }
}
