//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Contient les donn�es constitutives d'un bilan de cycle
 *             
 * 
 * <p>Java class for BilanCycle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BilanCycle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="socle">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="8" minOccurs="8">
 *                   &lt;element name="domaine" type="{urn:fr:edu:scolarite:lsun:bilans:import}DomaineSocleCycle"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="synthese" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine1500"/>
 *         &lt;element name="enseignement-complement" type="{urn:fr:edu:scolarite:lsun:bilans:import}EnseignementComplement" minOccurs="0"/>
 *         &lt;element name="responsables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="responsable" type="{urn:fr:edu:scolarite:lsun:bilans:import}Responsable"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="eleve-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="cycle" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Cycle" />
 *       &lt;attribute name="millesime" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Millesime" />
 *       &lt;attribute name="date-creation" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="date-verrou" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}StringDateTime" />
 *       &lt;attribute name="responsable-etab-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="prof-princ-refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BilanCycle", propOrder = {
    "socle",
    "synthese",
    "enseignementComplement",
    "responsables"
})
public class BilanCycle {

    @XmlElement(required = true)
    protected Socle socle;
    @XmlElement(required = true)
    protected String synthese;
    @XmlElement(name = "enseignement-complement")
    protected EnseignementComplement enseignementComplement;
    protected Responsables responsables;
    @XmlAttribute(name = "eleve-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object eleveRef;
    @XmlAttribute(name = "cycle", required = true)
    protected BigInteger cycle;
    @XmlAttribute(name = "millesime", required = true)
    protected String millesime;
    @XmlAttribute(name = "date-creation", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateCreation;
    @XmlAttribute(name = "date-verrou", required = true)
    protected String dateVerrou;
    @XmlAttribute(name = "responsable-etab-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object responsableEtabRef;
    @XmlAttribute(name = "prof-princ-refs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> profPrincRefs;

    /**
     * Gets the value of the socle property.
     * 
     * @return
     *     possible object is
     *     {@link Socle }
     *     
     */
    public Socle getSocle() {
        return socle;
    }

    /**
     * Sets the value of the socle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Socle }
     *     
     */
    public void setSocle(Socle value) {
        this.socle = value;
    }

    /**
     * Gets the value of the synthese property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSynthese() {
        return synthese;
    }

    /**
     * Sets the value of the synthese property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSynthese(String value) {
        //this.synthese = new String(value.getBytes(Charset.forName("UTF-8")));
        this.synthese = value;
    }

    /**
     * Gets the value of the enseignementComplement property.
     * 
     * @return
     *     possible object is
     *     {@link EnseignementComplement }
     *     
     */
    public EnseignementComplement getEnseignementComplement() {

        return enseignementComplement;
    }

    /**
     * Sets the value of the enseignementComplement property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnseignementComplement }
     *     
     */
    public void setEnseignementComplement(EnseignementComplement value) {


        this.enseignementComplement = value;
    }

    /**
     * Gets the value of the responsables property.
     * 
     * @return
     *     possible object is
     *     {@link Responsables }
     *     
     */
    public Responsables getResponsables() {
        return responsables;
    }

    /**
     * Sets the value of the responsables property.
     * 
     * @param value
     *     allowed object is
     *     {@link Responsables }
     *     
     */
    public void setResponsables(Responsables value) {
        this.responsables = value;
    }

    /**
     * Gets the value of the eleveRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEleveRef() {
        return eleveRef;
    }

    /**
     * Sets the value of the eleveRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEleveRef(Object value) {
        this.eleveRef = value;
    }

    /**
     * Gets the value of the cycle property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCycle() {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCycle(BigInteger value) {
        this.cycle = value;
    }

    /**
     * Gets the value of the millesime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMillesime() {
        return millesime;
    }

    /**
     * Sets the value of the millesime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMillesime(String value) {
        this.millesime = value;
    }

    /**
     * Gets the value of the dateCreation property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateCreation() {
        return dateCreation;
    }

    /**
     * Sets the value of the dateCreation property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateCreation(XMLGregorianCalendar value) {
        this.dateCreation = value;
    }

    /**
     * Gets the value of the dateVerrou property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateVerrou() {
        return dateVerrou;
    }

    /**
     * Sets the value of the dateVerrou property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateVerrou(String value) {
        this.dateVerrou = value;
    }

    /**
     * Gets the value of the responsableEtabRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getResponsableEtabRef() {
        return responsableEtabRef;
    }

    /**
     * Sets the value of the responsableEtabRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setResponsableEtabRef(Object value) {
        this.responsableEtabRef = value;
    }

    /**
     * Gets the value of the profPrincRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profPrincRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfPrincRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getProfPrincRefs() {
        if (profPrincRefs == null) {
            profPrincRefs = new ArrayList<Object>();
        }
        return this.profPrincRefs;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="responsable" type="{urn:fr:edu:scolarite:lsun:bilans:import}Responsable"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responsable"
    })
    public static class Responsables {

        @XmlElement(required = true)
        protected List<Responsable> responsable;

        /**
         * Gets the value of the responsable property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsable property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsable().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Responsable }
         * 
         * 
         */
        public List<Responsable> getResponsable() {
            if (responsable == null) {
                responsable = new ArrayList<Responsable>();
            }
            return this.responsable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="8" minOccurs="8">
     *         &lt;element name="domaine" type="{urn:fr:edu:scolarite:lsun:bilans:import}DomaineSocleCycle"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domaine"
    })
    public static class Socle {

        @XmlElement(required = true)
        protected List<DomaineSocleCycle> domaine;

        /**
         * Gets the value of the domaine property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domaine property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomaine().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DomaineSocleCycle }
         * 
         * 
         */
        public List<DomaineSocleCycle> getDomaine() {
            if (domaine == null) {
                domaine = new ArrayList<DomaineSocleCycle>();
            }
            return this.domaine;
        }

    }

}
