/*
 * Copyright (c) Région Hauts-de-France, Département de la Seine-et-Marne, CGI, 2016.
 *     This file is part of OPEN ENT NG. OPEN ENT NG is a versatile ENT Project based on the JVM and ENT Core Project.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as
 *   published by the Free Software Foundation (version 3 of the License).
 *   For the sake of explanation, any module that communicate over native
 *   Web protocols, such as HTTP, with OPEN ENT NG is outside the scope of this
 *   license and could be license under its own terms. This is merely considered
 *   normal use of OPEN ENT NG, and does not fall under the heading of "covered work".
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2017.07.06 at 05:11:16 PM CEST
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * Contient les donn�es d'un bilan p�riodique
 *
 * <p>Java class for BilanPeriodique complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BilanPeriodique">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="liste-acquis">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="acquis" type="{urn:fr:edu:scolarite:lsun:bilans:import}Acquis"/>
 *                  &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="competences-numeriques" minOccurs="0">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence minOccurs="0">
 *                     &lt;element name="appreciation-num" type="{urn:fr:edu:scolarite:lsun:bilans:import}ChaineEmptyWithMax600" minOccurs="0"/>
 *                     &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                       &lt;element name="competence-num" type="{urn:fr:edu:scolarite:lsun:bilans:import}CompetenceNumeriqueNiveau"/>
 *                     &lt;/sequence>
 *                   &lt;/sequence>
 *                  &lt;attribute name="comp-num-commun-refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="epis-eleve" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="epi-eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiEleve"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc-persos-eleve" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="acc-perso-eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPersoEleve"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="liste-parcours" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="parcours" type="{urn:fr:edu:scolarite:lsun:bilans:import}Parcours"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="modalites-accompagnement" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="modalite-accompagnement" type="{urn:fr:edu:scolarite:lsun:bilans:import}ModaliteAccompagnement"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acquis-conseils" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine1000"/>
 *         &lt;element name="devoirs-faits" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine600" minOccurs="0"/>
 *         &lt;element name="vie-scolaire" type="{urn:fr:edu:scolarite:lsun:bilans:import}VieScolaire"/>
 *         &lt;element name="socle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="8" minOccurs="8">
 *                   &lt;element name="domaine" type="{urn:fr:edu:scolarite:lsun:bilans:import}DomaineSocle"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="responsables" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="responsable" type="{urn:fr:edu:scolarite:lsun:bilans:import}Responsable"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="eleve-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="periode-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="date-conseil-classe" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="date-scolarite" use="required" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="date-verrou" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}StringDateTime" />
 *       &lt;attribute name="responsable-etab-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="prof-princ-refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BilanPeriodique", propOrder = {
    "listeAcquis",
    "competencesNumeriques",
    "episEleve",
    "accPersosEleve",
    "listeParcours",
    "modalitesAccompagnement",
    "acquisConseils",
    "devoirsFaits",
    "vieScolaire",
    "socle",
    "responsables"
})
public class BilanPeriodique {

    @XmlElement(name = "liste-acquis", required = true)
    protected BilanPeriodique.ListeAcquis listeAcquis;
    @XmlElement(name = "competences-numeriques")
    protected BilanPeriodique.CompetencesNumeriques competencesNumeriques;
    @XmlElement(name = "epis-eleve")
    protected BilanPeriodique.EpisEleve episEleve;
    @XmlElement(name = "acc-persos-eleve")
    protected BilanPeriodique.AccPersosEleve accPersosEleve;
    @XmlElement(name = "liste-parcours")
    protected BilanPeriodique.ListeParcours listeParcours;
    @XmlElement(name = "modalites-accompagnement")
    protected BilanPeriodique.ModalitesAccompagnement modalitesAccompagnement;
    @XmlElement(name = "acquis-conseils", required = true)
    protected String acquisConseils;
    @XmlElement(name = "devoirs-faits")
    protected String devoirsFaits;
    @XmlElement(name = "vie-scolaire", required = true)
    protected VieScolaire vieScolaire;
    protected BilanPeriodique.Socle socle;
    protected BilanPeriodique.Responsables responsables;
    @XmlAttribute(name = "eleve-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object eleveRef;
    @XmlAttribute(name = "periode-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object periodeRef;
    @XmlAttribute(name = "date-conseil-classe", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateConseilClasse;
    @XmlAttribute(name = "date-scolarite", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateScolarite;
    @XmlAttribute(name = "date-verrou", required = true)
    protected String dateVerrou;
    @XmlAttribute(name = "responsable-etab-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object responsableEtabRef;
    @XmlAttribute(name = "prof-princ-refs")
    @XmlIDREF
    @XmlSchemaType(name = "IDREFS")
    protected List<Object> profPrincRefs;

    /**
     * Gets the value of the listeAcquis property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.ListeAcquis }
     *
     */
    public BilanPeriodique.ListeAcquis getListeAcquis() {
        return listeAcquis;
    }

    /**
     * Sets the value of the listeAcquis property.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.ListeAcquis }
     *
     */
    public void setListeAcquis(BilanPeriodique.ListeAcquis value) {
        this.listeAcquis = value;
    }

    /**
     * Obtient la valeur de la propriété competencesNumeriques.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.CompetencesNumeriques }
     *
     */
    public BilanPeriodique.CompetencesNumeriques getCompetencesNumeriques() {
        return competencesNumeriques;
    }

    /**
     * Définit la valeur de la propriété competencesNumeriques.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.CompetencesNumeriques }
     *
     */
    public void setCompetencesNumeriques(BilanPeriodique.CompetencesNumeriques value) {
        this.competencesNumeriques = value;
    }

    /**
     * Gets the value of the episEleve property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.EpisEleve }
     *
     */
    public BilanPeriodique.EpisEleve getEpisEleve() {
        return episEleve;
    }

    /**
     * Sets the value of the episEleve property.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.EpisEleve }
     *
     */
    public void setEpisEleve(BilanPeriodique.EpisEleve value) {
        this.episEleve = value;
    }

    /**
     * Gets the value of the accPersosEleve property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.AccPersosEleve }
     *
     */
    public BilanPeriodique.AccPersosEleve getAccPersosEleve() {
        return accPersosEleve;
    }

    /**
     * Sets the value of the accPersosEleve property.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.AccPersosEleve }
     *
     */
    public void setAccPersosEleve(BilanPeriodique.AccPersosEleve value) {
        this.accPersosEleve = value;
    }

    /**
     * Gets the value of the listeParcours property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.ListeParcours }
     *
     */
    public BilanPeriodique.ListeParcours getListeParcours() {
        return listeParcours;
    }

    /**
     * Sets the value of the listeParcours property.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.ListeParcours }
     *
     */
    public void setListeParcours(BilanPeriodique.ListeParcours value) {
        this.listeParcours = value;
    }

    /**
     * Gets the value of the modalitesAccompagnement property.
     *
     * @return
     *     possible object is
     *     {@link ModalitesAccompagnement }
     *
     */
    public ModalitesAccompagnement getModalitesAccompagnement() {
        return modalitesAccompagnement;
    }

    /**
     * Sets the value of the modalitesAccompagnement property.
     *
     * @param value
     *     allowed object is
     *     {@link ModalitesAccompagnement }
     *
     */
    public void setModalitesAccompagnement(ModalitesAccompagnement value) {
        this.modalitesAccompagnement = value;
    }

    /**
     * Gets the value of the acquisConseils property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAcquisConseils() {
        return acquisConseils;
    }

    /**
     * Sets the value of the acquisConseils property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAcquisConseils(String value) {
        this.acquisConseils = value;
    }

    /**
     * Obtient la valeur de la propriété devoirsFaits.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDevoirsFaits() {
        return devoirsFaits;
    }

    /**
     * Définit la valeur de la propriété devoirsFaits.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDevoirsFaits(String value) {
        this.devoirsFaits = value;
    }

    /**
     * Gets the value of the vieScolaire property.
     *
     * @return
     *     possible object is
     *     {@link VieScolaire }
     *
     */
    public VieScolaire getVieScolaire() {
        return vieScolaire;
    }

    /**
     * Sets the value of the vieScolaire property.
     *
     * @param value
     *     allowed object is
     *     {@link VieScolaire }
     *
     */
    public void setVieScolaire(VieScolaire value) {
        this.vieScolaire = value;
    }

    /**
     * Gets the value of the socle property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.Socle }
     *
     */
    public BilanPeriodique.Socle getSocle() {
        return socle;
    }

    /**
     * Sets the value of the socle property.
     *
     * @param value
     *     allowed object is
     *     {@link BilanPeriodique.Socle }
     *
     */
    public void setSocle(BilanPeriodique.Socle value) {
        this.socle = value;
    }

    /**
     * Gets the value of the responsables property.
     *
     * @return
     *     possible object is
     *     {@link BilanPeriodique.Responsables }
     *
     */
    public BilanPeriodique.Responsables getResponsables() {
        return responsables;
    }

    /**
     * Sets the value of the responsables property.
     *
     * @param value
     *     allowed object is
     *     {@link Responsables }
     *
     */
    public void setResponsables(BilanPeriodique.Responsables value) {
        this.responsables = value;
    }

    /**
     * Gets the value of the eleveRef property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getEleveRef() {
        return eleveRef;
    }

    /**
     * Sets the value of the eleveRef property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setEleveRef(Object value) {
        this.eleveRef = value;
    }

    /**
     * Gets the value of the periodeRef property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getPeriodeRef() {
        return periodeRef;
    }

    /**
     * Sets the value of the periodeRef property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setPeriodeRef(Object value) {
        this.periodeRef = value;
    }

    /**
     * Gets the value of the dateConseilClasse property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateConseilClasse() {
        return dateConseilClasse;
    }

    /**
     * Sets the value of the dateConseilClasse property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateConseilClasse(XMLGregorianCalendar value) {
        this.dateConseilClasse = value;
    }

    /**
     * Gets the value of the dateScolarite property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getDateScolarite() {
        return dateScolarite;
    }

    /**
     * Sets the value of the dateScolarite property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setDateScolarite(XMLGregorianCalendar value) {
        this.dateScolarite = value;
    }

    /**
     * Gets the value of the dateVerrou property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getDateVerrou() {
        return dateVerrou;
    }

    /**
     * Sets the value of the dateVerrou property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setDateVerrou(String value) {
        this.dateVerrou = value;
    }

    /**
     * Gets the value of the responsableEtabRef property.
     *
     * @return
     *     possible object is
     *     {@link Object }
     *
     */
    public Object getResponsableEtabRef() {
        return responsableEtabRef;
    }

    /**
     * Sets the value of the responsableEtabRef property.
     *
     * @param value
     *     allowed object is
     *     {@link Object }
     *
     */
    public void setResponsableEtabRef(Object value) {
        this.responsableEtabRef = value;
    }

    /**
     * Gets the value of the profPrincRefs property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profPrincRefs property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfPrincRefs().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     *
     *
     */
    public List<Object> getProfPrincRefs() {
        if (profPrincRefs == null) {
            profPrincRefs = new ArrayList<Object>();
        }
        return this.profPrincRefs;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="acc-perso-eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPersoEleve"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accPersoEleve"
    })
    public static class AccPersosEleve {

        @XmlElement(name = "acc-perso-eleve", required = true)
        protected List<AccPersoEleve> accPersoEleve;

        /**
         * Gets the value of the accPersoEleve property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPersoEleve property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPersoEleve().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AccPersoEleve }
         *
         *
         */
        public List<AccPersoEleve> getAccPersoEleve() {
            if (accPersoEleve == null) {
                accPersoEleve = new ArrayList<AccPersoEleve>();
            }
            return this.accPersoEleve;
        }

    }

    /**
     * <p>Classe Java pour anonymous complex type.
     *
     * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="appreciation-num" type="{urn:fr:edu:scolarite:lsun:bilans:import}ChaineEmptyWithMax600" minOccurs="0"/>
     *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="competence-num" type="{urn:fr:edu:scolarite:lsun:bilans:import}CompetenceNumeriqueNiveau"/>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *       &lt;attribute name="comp-num-commun-refs" type="{http://www.w3.org/2001/XMLSchema}IDREFS" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "appreciationNum",
            "competenceNum"
    })
    public static class CompetencesNumeriques {

        @XmlElement(name = "appreciation-num")
        protected String appreciationNum;
        @XmlElement(name = "competence-num")
        protected List<CompetenceNumeriqueNiveau> competenceNum;
        @XmlAttribute(name = "comp-num-commun-refs")
        @XmlIDREF
        @XmlSchemaType(name = "IDREFS")
        protected List<Object> compNumCommunRefs;

        /**
         * Obtient la valeur de la propriété appreciationNum.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAppreciationNum() {
            return appreciationNum;
        }

        /**
         * Définit la valeur de la propriété appreciationNum.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAppreciationNum(String value) {
            this.appreciationNum = value;
        }

        /**
         * Gets the value of the competenceNum property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the competenceNum property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompetenceNum().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompetenceNumeriqueNiveau }
         *
         *
         */
        public List<CompetenceNumeriqueNiveau> getCompetenceNum() {
            if (competenceNum == null) {
                competenceNum = new ArrayList<CompetenceNumeriqueNiveau>();
            }
            return this.competenceNum;
        }

        /**
         * Gets the value of the compNumCommunRefs property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the compNumCommunRefs property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompNumCommunRefs().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Object }
         *
         *
         */
        public List<Object> getCompNumCommunRefs() {
            if (compNumCommunRefs == null) {
                compNumCommunRefs = new ArrayList<Object>();
            }
            return this.compNumCommunRefs;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="epi-eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiEleve"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "epiEleve"
    })
    public static class EpisEleve {

        @XmlElement(name = "epi-eleve", required = true)
        protected List<EpiEleve> epiEleve;

        /**
         * Gets the value of the epiEleve property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the epiEleve property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpiEleve().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EpiEleve }
         *
         *
         */
        public List<EpiEleve> getEpiEleve() {
            if (epiEleve == null) {
                epiEleve = new ArrayList<EpiEleve>();
            }
            return this.epiEleve;
        }


    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="acquis" type="{urn:fr:edu:scolarite:lsun:bilans:import}Acquis"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "acquis"
    })
    public static class ListeAcquis {

        @XmlElement(required = true)
        protected List<Acquis> acquis;

        /**
         * Gets the value of the acquis property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the acquis property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAcquis().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Acquis }
         *
         *
         */
        public List<Acquis> getAcquis() {
            if (acquis == null) {
                acquis = new ArrayList<Acquis>();
            }
            return this.acquis;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="parcours" type="{urn:fr:edu:scolarite:lsun:bilans:import}Parcours"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parcours"
    })
    public static class ListeParcours {

        @XmlElement(required = true)
        protected List<Parcours> parcours;

        /**
         * Gets the value of the parcours property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parcours property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParcours().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Parcours }
         *
         *
         */
        public List<Parcours> getParcours() {
            if (parcours == null) {
                parcours = new ArrayList<Parcours>();
            }
            return this.parcours;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="modalite-accompagnement" type="{urn:fr:edu:scolarite:lsun:bilans:import}ModaliteAccompagnement"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "modaliteAccompagnement"
    })
    public static class ModalitesAccompagnement {

        @XmlElement(name = "modalite-accompagnement", required = true)
        protected List<ModaliteAccompagnement> modaliteAccompagnement;

        /**
         * Gets the value of the modaliteAccompagnement property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the modaliteAccompagnement property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getModaliteAccompagnement().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ModaliteAccompagnement }
         *
         *
         */
        public List<ModaliteAccompagnement> getModaliteAccompagnement() {
            if (modaliteAccompagnement == null) {
                modaliteAccompagnement = new ArrayList<ModaliteAccompagnement>();
            }
            return this.modaliteAccompagnement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="responsable" type="{urn:fr:edu:scolarite:lsun:bilans:import}Responsable"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responsable"
    })
    public static class Responsables {

        @XmlElement(required = true)
        protected List<Responsable> responsable;

        /**
         * Gets the value of the responsable property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsable property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsable().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Responsable }
         *
         *
         */
        public List<Responsable> getResponsable() {
            if (responsable == null) {
                responsable = new ArrayList<Responsable>();
            }
            return this.responsable;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="8" minOccurs="8">
     *         &lt;element name="domaine" type="{urn:fr:edu:scolarite:lsun:bilans:import}DomaineSocle"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "domaine"
    })
    public static class Socle {

        @XmlElement(required = true)
        protected List<DomaineSocle> domaine;

        /**
         * Gets the value of the domaine property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the domaine property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDomaine().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DomaineSocle }
         *
         *
         */
        public List<DomaineSocle> getDomaine() {
            if (domaine == null) {
                domaine = new ArrayList<DomaineSocle>();
            }
            return this.domaine;
        }

    }

}
