//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Contient les informations relatives � la discpline
 *                 (le code doit correspondre � un code de mati�re nationale)
 *             
 * 
 * <p>Java class for Discipline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Discipline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="code" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeMatiere" />
 *       &lt;attribute name="code-national" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeMatiere" />
 *       &lt;attribute name="modalite-election" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}ModaliteElection" />
 *       &lt;attribute name="libelle" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine40" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Discipline")
public class Discipline {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "code", required = true)
    protected String code;
    @XmlAttribute(name = "code-national")
    protected String codeNational;
    @XmlAttribute(name = "modalite-election", required = true)
    protected ModaliteElection modaliteElection;
    @XmlAttribute(name = "libelle", required = true)
    protected String libelle;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the codeNational property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodeNational() {
        return codeNational;
    }

    /**
     * Sets the value of the codeNational property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodeNational(String value) {
        this.codeNational = value;
    }

    /**
     * Gets the value of the modaliteElection property.
     * 
     * @return
     *     possible object is
     *     {@link ModaliteElection }
     *     
     */
    public ModaliteElection getModaliteElection() {
        return modaliteElection;
    }

    /**
     * Sets the value of the modaliteElection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModaliteElection }
     *     
     */
    public void setModaliteElection(ModaliteElection value) {
        this.modaliteElection = value;
    }

    /**
     * Gets the value of the libelle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLibelle() {
        return libelle;
    }

    /**
     * Sets the value of the libelle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLibelle(String value) {
        this.libelle = value;
    }

}
