//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * D�crit le positionnement de l'�l�ve sur les domaines du socle commun dans les bilans de cycle
 *             
 * 
 * <p>Java class for DomaineSocleCycle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DomaineSocleCycle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="code" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeDomaineSocle" />
 *       &lt;attribute name="positionnement" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}PositionnementSocle" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DomaineSocleCycle")
public class DomaineSocleCycle {

    @XmlAttribute(name = "code", required = true)
    protected CodeDomaineSocle code;
    @XmlAttribute(name = "positionnement", required = true)
    protected BigInteger positionnement;


    public DomaineSocleCycle(){}
    public DomaineSocleCycle(String code, Integer positionnenement){
        this.code = CodeDomaineSocle.fromValue(code);
        this.positionnement = BigInteger.valueOf(positionnenement);
    }
    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeDomaineSocle }
     *     
     */
    public CodeDomaineSocle getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeDomaineSocle }
     *     
     */
    public void setCode(CodeDomaineSocle value) {
        this.code = value;
    }

    /**
     * Gets the value of the positionnement property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionnement() {
        return positionnement;
    }

    /**
     * Sets the value of the positionnement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionnement(BigInteger value) {
        this.positionnement = value;
    }

}
