/*
 * Copyright (c) Région Hauts-de-France, Département de la Seine-et-Marne, CGI, 2016.
 *     This file is part of OPEN ENT NG. OPEN ENT NG is a versatile ENT Project based on the JVM and ENT Core Project.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as
 *   published by the Free Software Foundation (version 3 of the License).
 *   For the sake of explanation, any module that communicate over native
 *   Web protocols, such as HTTP, with OPEN ENT NG is outside the scope of this
 *   license and could be license under its own terms. This is merely considered
 *   normal use of OPEN ENT NG, and does not fall under the heading of "covered work".
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;


/**
 * Contient les donn�es constitutives des bilans
 *
 *
 * <p>Java class for Donnees complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Donnees">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="responsables-etab">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="responsable-etab" type="{urn:fr:edu:scolarite:lsun:bilans:import}ResponsableEtab"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="eleves">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}Eleve"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="periodes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="periode" type="{urn:fr:edu:scolarite:lsun:bilans:import}Periode"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="disciplines" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="discipline" type="{urn:fr:edu:scolarite:lsun:bilans:import}Discipline"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="enseignants" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="enseignant" type="{urn:fr:edu:scolarite:lsun:bilans:import}Enseignant"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="elements-programme" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="element-programme" type="{urn:fr:edu:scolarite:lsun:bilans:import}ElementProgramme"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="competences-numeriques-communs" minOccurs="0">
 *           &lt;complexType>
 *              &lt;complexContent>
 *                &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                  &lt;sequence maxOccurs="unbounded">
 *                    &lt;element name="competences-numeriques-commun" type="{urn:fr:edu:scolarite:lsun:bilans:import}CompetencesNumeriquesCommun"/>
 *                  &lt;/sequence>
 *                &lt;/restriction>
 *              &lt;/complexContent>
 *            &lt;/complexType>
 *          &lt;/element>
 *         &lt;element name="parcours-communs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="parcours-commun">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence maxOccurs="unbounded">
 *                             &lt;element name="parcours" type="{urn:fr:edu:scolarite:lsun:bilans:import}Parcours"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="periode-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                           &lt;attribute name="code-division" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeStructure" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vies-scolaires-communs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="vie-scolaire-commun" type="{urn:fr:edu:scolarite:lsun:bilans:import}VieScolaireCommun"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="epis-thematiques" minOccurs="0">
 *           &lt;complexType>
 *              &lt;complexContent>
 *                &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                  &lt;sequence maxOccurs="unbounded">
 *                    &lt;element name="epi-thematique" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiThematique"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;element name="epis" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="epi" type="{urn:fr:edu:scolarite:lsun:bilans:import}Epi"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="epis-groupes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="epi-groupe" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiGroupe"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc-persos" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="acc-perso" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPerso"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="acc-persos-groupes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="acc-perso-groupe" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPersoGroupe"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bilans-periodiques" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="bilan-periodique" type="{urn:fr:edu:scolarite:lsun:bilans:import}BilanPeriodique" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="bilans-cycle" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="bilan-cycle" type="{urn:fr:edu:scolarite:lsun:bilans:import}BilanCycle"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Donnees", propOrder = {
        "responsablesEtab",
        "eleves",
        "periodes",
        "disciplines",
        "enseignants",
        "elementsProgramme",
        "competencesNumeriquesCommuns",
        "parcoursCommuns",
        "viesScolairesCommuns",
        "episThematiques",
        "epis",
        "episGroupes",
        "accPersos",
        "accPersosGroupes",
        "bilansPeriodiques",
        "bilansCycle"
})
public class Donnees {

    @XmlElement(name = "responsables-etab", required = true)
    protected Donnees.ResponsablesEtab responsablesEtab;
    @XmlElement(required = true)
    protected Donnees.Eleves eleves;
    protected Donnees.Periodes periodes;
    protected Donnees.Disciplines disciplines;
    protected Donnees.Enseignants enseignants;
    @XmlElement(name = "elements-programme")
    protected Donnees.ElementsProgramme elementsProgramme;
    @XmlElement(name = "competences-numeriques-communs")
    protected Donnees.CompetencesNumeriquesCommuns competencesNumeriquesCommuns;
    @XmlElement(name = "parcours-communs")
    protected Donnees.ParcoursCommuns parcoursCommuns;
    @XmlElement(name = "vies-scolaires-communs")
    protected Donnees.ViesScolairesCommuns viesScolairesCommuns;
    @XmlElement(name = "epis-thematiques")
    protected Donnees.EpisThematiques episThematiques;
    protected Donnees.Epis epis;
    @XmlElement(name = "epis-groupes")
    protected Donnees.EpisGroupes episGroupes;
    @XmlElement(name = "acc-persos")
    protected Donnees.AccPersos accPersos;
    @XmlElement(name = "acc-persos-groupes")
    protected Donnees.AccPersosGroupes accPersosGroupes;
    @XmlElement(name = "bilans-periodiques")
    protected Donnees.BilansPeriodiques bilansPeriodiques;
    @XmlElement(name = "bilans-cycle")
    protected Donnees.BilansCycle bilansCycle;

    /**
     * Gets the value of the responsablesEtab property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.ResponsablesEtab }
     *
     */
    public Donnees.ResponsablesEtab getResponsablesEtab() {
        return responsablesEtab;
    }

    /**
     * Sets the value of the responsablesEtab property.
     *
     * @param value
     *     allowed object is
     *     {@link ResponsablesEtab }
     *
     */
    public void setResponsablesEtab(Donnees.ResponsablesEtab value) {
        this.responsablesEtab = value;
    }

    /**
     * Gets the value of the eleves property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.Eleves }
     *
     */
    public Donnees.Eleves getEleves() {
        return eleves;
    }

    /**
     * Sets the value of the eleves property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.Eleves }
     *
     */
    public void setEleves(Donnees.Eleves value) {
        this.eleves = value;
    }

    /**
     * Gets the value of the periodes property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.Periodes }
     *
     */
    public Donnees.Periodes getPeriodes() {
        return periodes;
    }

    /**
     * Sets the value of the periodes property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.Periodes }
     *
     */
    public void setPeriodes(Donnees.Periodes value) {
        this.periodes = value;
    }

    /**
     * Gets the value of the disciplines property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.Disciplines }
     *
     */
    public Donnees.Disciplines getDisciplines() {
        return disciplines;
    }

    /**
     * Sets the value of the disciplines property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.Disciplines }
     *
     */
    public void setDisciplines(Donnees.Disciplines value) {
        this.disciplines = value;
    }

    /**
     * Gets the value of the enseignants property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.Enseignants }
     *
     */
    public Donnees.Enseignants getEnseignants() {
        return enseignants;
    }

    /**
     * Sets the value of the enseignants property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.Enseignants }
     *
     */
    public void setEnseignants(Donnees.Enseignants value) {
        this.enseignants = value;
    }

    /**
     * Gets the value of the elementsProgramme property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.ElementsProgramme }
     *
     */
    public Donnees.ElementsProgramme getElementsProgramme() {
        return elementsProgramme;
    }

    /**
     * Sets the value of the elementsProgramme property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.ElementsProgramme }
     *
     */
    public void setElementsProgramme(Donnees.ElementsProgramme value) {
        this.elementsProgramme = value;
    }

    /**
     * Obtient la valeur de la propriété competencesNumeriquesCommuns.
     *
     * @return
     *     possible object is
     *     {@link Donnees.CompetencesNumeriquesCommuns }
     *
     */
    public Donnees.CompetencesNumeriquesCommuns getCompetencesNumeriquesCommuns() {
        return competencesNumeriquesCommuns;
    }

    /**
     * Définit la valeur de la propriété competencesNumeriquesCommuns.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.CompetencesNumeriquesCommuns }
     *
     */
    public void setCompetencesNumeriquesCommuns(Donnees.CompetencesNumeriquesCommuns value) {
        this.competencesNumeriquesCommuns = value;
    }


    /**
     * Gets the value of the parcoursCommuns property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.ParcoursCommuns }
     *
     */
    public Donnees.ParcoursCommuns getParcoursCommuns() {
        return parcoursCommuns;
    }

    /**
     * Sets the value of the parcoursCommuns property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.ParcoursCommuns }
     *
     */
    public void setParcoursCommuns(Donnees.ParcoursCommuns value) {
        this.parcoursCommuns = value;
    }

    /**
     * Gets the value of the viesScolairesCommuns property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.ViesScolairesCommuns }
     *
     */
    public Donnees.ViesScolairesCommuns getViesScolairesCommuns() {
        return viesScolairesCommuns;
    }

    /**
     * Sets the value of the viesScolairesCommuns property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.ViesScolairesCommuns }
     *
     */
    public void setViesScolairesCommuns(Donnees.ViesScolairesCommuns value) {
        this.viesScolairesCommuns = value;
    }

    /**
     * Obtient la valeur de la propriété episThematiques.
     *
     * @return
     *     possible object is
     *     {@link Donnees.EpisThematiques }
     *
     */
    public Donnees.EpisThematiques getEpisThematiques() {
        return episThematiques;
    }

    /**
     * Définit la valeur de la propriété episThematiques.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.EpisThematiques }
     *
     */
    public void setEpisThematiques(Donnees.EpisThematiques value) {
        this.episThematiques = value;
    }

    /**
     * Gets the value of the epis property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.Epis }
     *
     */
    public Donnees.Epis getEpis() {
        return epis;
    }

    /**
     * Sets the value of the epis property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.Epis }
     *
     */
    public void setEpis(Donnees.Epis value) {
        this.epis = value;
    }

    /**
     * Gets the value of the episGroupes property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.EpisGroupes }
     *
     */
    public Donnees.EpisGroupes getEpisGroupes() {
        return episGroupes;
    }

    /**
     * Sets the value of the episGroupes property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.EpisGroupes }
     *
     */
    public void setEpisGroupes(Donnees.EpisGroupes value) {
        this.episGroupes = value;
    }

    /**
     * Gets the value of the accPersos property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.AccPersos }
     *
     */
    public Donnees.AccPersos getAccPersos() {
        return accPersos;
    }

    /**
     * Sets the value of the accPersos property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.AccPersos }
     *
     */
    public void setAccPersos(Donnees.AccPersos value) {
        this.accPersos = value;
    }

    /**
     * Gets the value of the accPersosGroupes property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.AccPersosGroupes }
     *
     */
    public Donnees.AccPersosGroupes getAccPersosGroupes() {
        return accPersosGroupes;
    }

    /**
     * Sets the value of the accPersosGroupes property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.AccPersosGroupes }
     *
     */
    public void setAccPersosGroupes(Donnees.AccPersosGroupes value) {
        this.accPersosGroupes = value;
    }

    /**
     * Gets the value of the bilansPeriodiques property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.BilansPeriodiques }
     *
     */
    public Donnees.BilansPeriodiques getBilansPeriodiques() {
        return bilansPeriodiques;
    }

    /**
     * Sets the value of the bilansPeriodiques property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.BilansPeriodiques }
     *
     */
    public void setBilansPeriodiques(Donnees.BilansPeriodiques value) {
        this.bilansPeriodiques = value;
    }

    /**
     * Gets the value of the bilansCycle property.
     *
     * @return
     *     possible object is
     *     {@link Donnees.BilansCycle }
     *
     */
    public Donnees.BilansCycle getBilansCycle() {
        return bilansCycle;
    }

    /**
     * Sets the value of the bilansCycle property.
     *
     * @param value
     *     allowed object is
     *     {@link Donnees.BilansCycle }
     *
     */
    public void setBilansCycle(Donnees.BilansCycle value) {
        this.bilansCycle = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="acc-perso" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPerso"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accPerso"
    })
    public static class AccPersos {

        @XmlElement(name = "acc-perso", required = true)
        protected List<AccPerso> accPerso;

        /**
         * Gets the value of the accPerso property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPerso property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPerso().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AccPerso }
         *
         *
         */
        public List<AccPerso> getAccPerso() {
            if (accPerso == null) {
                accPerso = new ArrayList<AccPerso>();
            }
            return this.accPerso;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="acc-perso-groupe" type="{urn:fr:edu:scolarite:lsun:bilans:import}AccPersoGroupe"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "accPersoGroupe"
    })
    public static class AccPersosGroupes {

        @XmlElement(name = "acc-perso-groupe", required = true)
        protected List<AccPersoGroupe> accPersoGroupe;

        /**
         * Gets the value of the accPersoGroupe property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPersoGroupe property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPersoGroupe().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AccPersoGroupe }
         *
         *
         */
        public List<AccPersoGroupe> getAccPersoGroupe() {
            if (accPersoGroupe == null) {
                accPersoGroupe = new ArrayList<AccPersoGroupe>();
            }
            return this.accPersoGroupe;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="bilan-cycle" type="{urn:fr:edu:scolarite:lsun:bilans:import}BilanCycle"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bilanCycle"
    })
    public static class BilansCycle {

        @XmlElement(name = "bilan-cycle", required = true)
        protected List<BilanCycle> bilanCycle;

        /**
         * Gets the value of the bilanCycle property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bilanCycle property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBilanCycle().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BilanCycle }
         *
         *
         */
        public List<BilanCycle> getBilanCycle() {
            if (bilanCycle == null) {
                bilanCycle = new ArrayList<BilanCycle>();
            }
            return this.bilanCycle;
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="bilan-periodique" type="{urn:fr:edu:scolarite:lsun:bilans:import}BilanPeriodique" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bilanPeriodique"
    })
    public static class BilansPeriodiques {

        @XmlElement(name = "bilan-periodique", required = true)
        protected List<BilanPeriodique> bilanPeriodique;

        /**
         * Gets the value of the bilanPeriodique property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the bilanPeriodique property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBilanPeriodique().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BilanPeriodique }
         *
         *
         */
        public List<BilanPeriodique> getBilanPeriodique() {
            if (bilanPeriodique == null) {
                bilanPeriodique = new ArrayList<BilanPeriodique>();
            }
            return this.bilanPeriodique;
        }

    }


    /**
     * <p>Classe Java pour anonymous complex type.
     *
     * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="competences-numeriques-commun" type="{urn:fr:edu:scolarite:lsun:bilans:import}CompetencesNumeriquesCommun"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "competencesNumeriquesCommun"
    })
    public static class CompetencesNumeriquesCommuns {

        @XmlElement(name = "competences-numeriques-commun", required = true)
        protected List<CompetencesNumeriquesCommun> competencesNumeriquesCommun;

        /**
         * Gets the value of the competencesNumeriquesCommun property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the competencesNumeriquesCommun property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCompetencesNumeriquesCommun().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CompetencesNumeriquesCommun }
         *
         *
         */
        public List<CompetencesNumeriquesCommun> getCompetencesNumeriquesCommun() {
            if (competencesNumeriquesCommun == null) {
                competencesNumeriquesCommun = new ArrayList<CompetencesNumeriquesCommun>();
            }
            return this.competencesNumeriquesCommun;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="discipline" type="{urn:fr:edu:scolarite:lsun:bilans:import}Discipline"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "discipline"
    })
    public static class Disciplines {

        @XmlElement(required = true)
        protected List<Discipline> discipline;

        /**
         * Gets the value of the discipline property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the discipline property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDiscipline().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Discipline }
         *
         *
         */
        public List<Discipline> getDiscipline() {
            if (discipline == null) {
                discipline = new ArrayList<Discipline>();
            }
            return this.discipline;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="element-programme" type="{urn:fr:edu:scolarite:lsun:bilans:import}ElementProgramme"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementProgramme"
    })
    public static class ElementsProgramme {

        @XmlElement(name = "element-programme", required = true)
        protected List<ElementProgramme> elementProgramme;

        /**
         * Gets the value of the elementProgramme property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementProgramme property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementProgramme().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ElementProgramme }
         *
         *
         */
        public List<ElementProgramme> getElementProgramme() {
            if (elementProgramme == null) {
                elementProgramme = new ArrayList<ElementProgramme>();
            }
            return this.elementProgramme;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="eleve" type="{urn:fr:edu:scolarite:lsun:bilans:import}Eleve"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eleve"
    })
    public static class Eleves {

        @XmlElement(required = true)
        protected List<Eleve> eleve;

        public Eleves (){
            eleve = new ArrayList<>();
        }
        /**
         * Gets the value of the eleve property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eleve property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEleve().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Eleve }
         *
         *
         */

        public List<Eleve> getEleve() {
            if (eleve == null) {
                eleve = new ArrayList<Eleve>();
            }
            return this.eleve;
        }

        public boolean containIdEleve(String idNeo4j){

                for(Eleve el: eleve){
                    if( el.getIdNeo4j().equals(idNeo4j)){
                        return true;
                    }
                }
            return false;
        }
        public Eleve getEleveById(String idNeo4j){

            for(Eleve el: eleve){
                if( el.getIdNeo4j().equals(idNeo4j)){
                    return el;
                }
            }
            return null;
        }
        public Map<String,List<String>> getMapIdClassIdsEleve(){
            Map<String,List<String>> mapIdClassIdEleve=new LinkedHashMap<>();
           // List<String> idsEleve =new ArrayList<>();

            for(Eleve el: eleve){

                if(!mapIdClassIdEleve.containsKey(el.getId_Class())){
                    List<String> idsEleve =new ArrayList<>();
                    idsEleve.add(el.getIdNeo4j());
                    mapIdClassIdEleve.put(el.getId_Class(),idsEleve);
                }else{
                    List<String> idsEleve = mapIdClassIdEleve.get(el.getId_Class());
                    idsEleve.add(el.getIdNeo4j());
                }
            }
            return mapIdClassIdEleve;
        }

        public List<String> getAllCodeDivision(){
            List<String> listCodeDivision = new ArrayList<>();
            for(Eleve eleve : eleve){
                if(!listCodeDivision.contains(eleve.getCodeDivision())){
                    listCodeDivision.add(eleve.getCodeDivision());
                }
            }
        return listCodeDivision;
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="enseignant" type="{urn:fr:edu:scolarite:lsun:bilans:import}Enseignant"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enseignant"
    })
    public static class Enseignants {

        @XmlElement(required = true)
        protected List<Enseignant> enseignant;

        /**
         * Gets the value of the enseignant property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the enseignant property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEnseignant().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Enseignant }
         *
         *
         */
        public List<Enseignant> getEnseignant() {
            if (enseignant == null) {
                enseignant = new ArrayList<Enseignant>();
            }
            return this.enseignant;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="epi" type="{urn:fr:edu:scolarite:lsun:bilans:import}Epi"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "epi"
    })
    public static class Epis {

        @XmlElement(required = true)
        protected List<Epi> epi;

        /**
         * Gets the value of the epi property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the epi property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpi().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Epi }
         *
         *
         */
        public List<Epi> getEpi() {
            if (epi == null) {
                epi = new ArrayList<Epi>();
            }
            return this.epi;
        }

        public boolean contains(Epi newEpi){

            boolean b = false;
            for(Epi epiItem : this.getEpi()){
                if( newEpi != null && epiItem.getId().equals(newEpi.getId())) b = true;
            }

            return b;
        }
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="epi-groupe" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiGroupe"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "epiGroupe"
    })
    public static class EpisGroupes {

        @XmlElement(name = "epi-groupe", required = true)
        protected List<EpiGroupe> epiGroupe;

        /**
         * Gets the value of the epiGroupe property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the epiGroupe property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpiGroupe().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EpiGroupe }
         *
         *
         */
        public List<EpiGroupe> getEpiGroupe() {
            if (epiGroupe == null) {
                epiGroupe = new ArrayList<EpiGroupe>();
            }
            return this.epiGroupe;
        }

    }


    /**
     * <p>Classe Java pour anonymous complex type.
     *
     * <p>Le fragment de schéma suivant indique le contenu attendu figurant dans cette classe.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="epi-thematique" type="{urn:fr:edu:scolarite:lsun:bilans:import}EpiThematique"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "epiThematique"
    })
    public static class EpisThematiques {

        @XmlElement(name = "epi-thematique", required = true)
        protected List<EpiThematique> epiThematique;

        /**
         * Gets the value of the epiThematique property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the epiThematique property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEpiThematique().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EpiThematique }
         *
         *
         */
        public List<EpiThematique> getEpiThematique() {
            if (epiThematique == null) {
                epiThematique = new ArrayList<EpiThematique>();
            }
            return this.epiThematique;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="parcours-commun">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence maxOccurs="unbounded">
     *                   &lt;element name="parcours" type="{urn:fr:edu:scolarite:lsun:bilans:import}Parcours"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="periode-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *                 &lt;attribute name="code-division" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeStructure" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parcoursCommun"
    })
    public static class ParcoursCommuns {

        @XmlElement(name = "parcours-commun", required = true)
        protected List<Donnees.ParcoursCommuns.ParcoursCommun> parcoursCommun;

        /**
         * Gets the value of the parcoursCommun property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the parcoursCommun property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParcoursCommun().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Donnees.ParcoursCommuns.ParcoursCommun }
         *
         *
         */
        public List<Donnees.ParcoursCommuns.ParcoursCommun> getParcoursCommun() {
            if (parcoursCommun == null) {
                parcoursCommun = new ArrayList<Donnees.ParcoursCommuns.ParcoursCommun>();
            }
            return this.parcoursCommun;
        }

        public Donnees.ParcoursCommuns.ParcoursCommun getParcoursCommunInList(Object periode, String codeDivision){

            ParcoursCommun parcoursCommun = null;
            if(this.parcoursCommun != null) {
                for (ParcoursCommun pc : this.parcoursCommun) {
                    if (pc.getCodeDivision().equals(codeDivision) && pc.getPeriodeRef().equals(periode)) {
                        parcoursCommun = pc;
                    }
                }
            }
            return parcoursCommun;
        }


        /**
         * Contient les parcours �ducatifs communs � une classe
         *
         *
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence maxOccurs="unbounded">
         *         &lt;element name="parcours" type="{urn:fr:edu:scolarite:lsun:bilans:import}Parcours"/>
         *       &lt;/sequence>
         *       &lt;attribute name="periode-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *       &lt;attribute name="code-division" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeStructure" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "parcours"
        })
        public static class ParcoursCommun {

            @XmlElement(required = true)
            protected List<Parcours> parcours;
            @XmlAttribute(name = "periode-ref", required = true)
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected Object periodeRef;
            @XmlAttribute(name = "code-division", required = true)
            protected String codeDivision;

            /**
             * Gets the value of the parcours property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the parcours property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getParcours().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Parcours }
             *
             *
             */
            public List<Parcours> getParcours() {
                if (parcours == null) {
                    parcours = new ArrayList<Parcours>();
                }
                return this.parcours;
            }

            /**
             * Gets the value of the periodeRef property.
             *
             * @return
             *     possible object is
             *     {@link Object }
             *
             */
            public Object getPeriodeRef() {
                return periodeRef;
            }

            /**
             * Sets the value of the periodeRef property.
             *
             * @param value
             *     allowed object is
             *     {@link Object }
             *
             */
            public void setPeriodeRef(Object value) {
                this.periodeRef = value;
            }

            /**
             * Gets the value of the codeDivision property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getCodeDivision() {
                return codeDivision;
            }

            /**
             * Sets the value of the codeDivision property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setCodeDivision(String value) {
                this.codeDivision = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="periode" type="{urn:fr:edu:scolarite:lsun:bilans:import}Periode"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "periode"
    })
    public static class Periodes {

        @XmlElement(required = true)
        protected List<Periode> periode;

        /**
         * Gets the value of the periode property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the periode property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPeriode().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Periode }
         *
         *
         */
        public List<Periode> getPeriode() {
            if (periode == null) {
                periode = new ArrayList<Periode>();
            }
            return this.periode;
        }
        public Periode getOnePeriode(String millesime, Integer indice, Integer nbPeriode){
            Periode periodeReturned = null;
            if(this.periode != null && this.periode.size() > 0){
                for (Periode p : periode){
                    if(p.getMillesime().equals(millesime) && p.getIndice() == indice && p.getNbPeriodes() == nbPeriode){
                        periodeReturned = p ;
                    }
                }
            }
            return periodeReturned;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="responsable-etab" type="{urn:fr:edu:scolarite:lsun:bilans:import}ResponsableEtab"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "responsableEtab"
    })
    public static class ResponsablesEtab {

        @XmlElement(name = "responsable-etab", required = true)
        protected List<ResponsableEtab> responsableEtab;

        /**
         * Gets the value of the responsableEtab property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the responsableEtab property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResponsableEtab().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResponsableEtab }
         *
         *
         */
        public List<ResponsableEtab> getResponsableEtab() {
            if (responsableEtab == null) {
                responsableEtab = new ArrayList<ResponsableEtab>();
            }
            return this.responsableEtab;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="vie-scolaire-commun" type="{urn:fr:edu:scolarite:lsun:bilans:import}VieScolaireCommun"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "vieScolaireCommun"
    })
    public static class ViesScolairesCommuns {

        @XmlElement(name = "vie-scolaire-commun", required = true)
        protected List<VieScolaireCommun> vieScolaireCommun;

        /**
         * Gets the value of the vieScolaireCommun property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vieScolaireCommun property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVieScolaireCommun().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link VieScolaireCommun }
         *
         *
         */
        public List<VieScolaireCommun> getVieScolaireCommun() {
            if (vieScolaireCommun == null) {
                vieScolaireCommun = new ArrayList<VieScolaireCommun>();
            }
            return this.vieScolaireCommun;
        }

    }

}
