/*
 * Copyright (c) Région Hauts-de-France, Département de la Seine-et-Marne, CGI, 2016.
 *     This file is part of OPEN ENT NG. OPEN ENT NG is a versatile ENT Project based on the JVM and ENT Core Project.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as
 *   published by the Free Software Foundation (version 3 of the License).
 *   For the sake of explanation, any module that communicate over native
 *   Web protocols, such as HTTP, with OPEN ENT NG is outside the scope of this
 *   license and could be license under its own terms. This is merely considered
 *   normal use of OPEN ENT NG, and does not fall under the heading of "covered work".
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * D�crit l'enseignement de compl�ment associ� au bilan de cycle
 *             
 * 
 * <p>Java class for EnseignementComplement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnseignementComplement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="code" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeEnsCompl" />
 *       &lt;attribute name="positionnement" type="{urn:fr:edu:scolarite:lsun:bilans:import}PositionnementEnsCompl" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnseignementComplement")
public class EnseignementComplement {

    @XmlAttribute(name = "code", required = true)
    protected CodeEnsCompl code;
    @XmlAttribute(name = "positionnement")
    protected BigInteger positionnement;

    public EnseignementComplement(){}
    public EnseignementComplement(String code,Integer niveau){

        if(niveau.equals(0)){
            this.code = CodeEnsCompl.fromValue(code);
        }else{
            this.code = CodeEnsCompl.fromValue(code);
            this.positionnement = BigInteger.valueOf(niveau);
        }
    }
        /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeEnsCompl }
     *     
     */
    public CodeEnsCompl getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeEnsCompl }
     *     
     */
    public void setCode(CodeEnsCompl value) {
        this.code = value;
    }

    /**
     * Gets the value of the positionnement property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPositionnement() {
        return positionnement;
    }

    /**
     * Sets the value of the positionnement property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPositionnement(BigInteger value) {
        this.positionnement = value;
    }

}
