//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;


/**
 * Contient un couple enseignant / discipline
 * 
 * <p>Java class for EnseignantDiscipline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnseignantDiscipline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="enseignant-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="discipline-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnseignantDiscipline")
public class EnseignantDiscipline {

    @XmlAttribute(name = "enseignant-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object enseignantRef;
    @XmlAttribute(name = "discipline-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object disciplineRef;

    /**
     * Gets the value of the enseignantRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEnseignantRef() {
        return enseignantRef;
    }

    /**
     * Sets the value of the enseignantRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEnseignantRef(Object value) {
        this.enseignantRef = value;
    }

    /**
     * Gets the value of the disciplineRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getDisciplineRef() {
        return disciplineRef;
    }

    /**
     * Sets the value of the disciplineRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setDisciplineRef(Object value) {
        this.disciplineRef = value;
    }

}
