//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contient les m�ta-donn�es requises au traitement du fichier d'import
 *             
 * 
 * <p>Java class for Entete complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Entete">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="editeur" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50"/>
 *         &lt;element name="application" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine50"/>
 *         &lt;element name="etablissement" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeUai"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entete", propOrder = {

})
public class Entete {

    @XmlElement(required = true)
    protected String editeur;
    @XmlElement(required = true)
    protected String application;
    @XmlElement(required = true)
    protected String etablissement;

    public Entete(String editeur, String application, String etablissement) {
        this.editeur = editeur;
        this.application = application;
        this.etablissement = etablissement;
    }
    public Entete (){}


    /**
     * Gets the value of the editeur property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditeur() {
        return editeur;
    }

    /**
     * Sets the value of the editeur property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditeur(String value) {
        this.editeur = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplication() {
        return application;
    }

    /**
     * Sets the value of the application property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplication(String value) {
        this.application = value;
    }

    /**
     * Gets the value of the etablissement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEtablissement() {
        return etablissement;
    }

    /**
     * Sets the value of the etablissement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEtablissement(String value) {
        this.etablissement = value;
    }

}
