//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * Contient l'intitul�, la th�matique, la description et les disciplines
 *             de l'EPI (enseignement pratique inter-disciplinaire)
 *             
 * 
 * <p>Java class for Epi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Epi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine600" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="intitule" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine150" />
 *       &lt;attribute name="thematique" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}ThematiqueEpi" />
 *       &lt;attribute name="discipline-refs" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}AtLeast2IDREFS" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Epi", propOrder = {
    "description"
})
public class Epi {

    protected String description;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "intitule", required = true)
    protected String intitule;
    @XmlAttribute(name = "thematique", required = true)
    protected ThematiqueEpi thematique;
    @XmlAttribute(name = "discipline-refs", required = true)
    @XmlIDREF
    protected List<Object> disciplineRefs;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the intitule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntitule() {
        return intitule;
    }

    /**
     * Sets the value of the intitule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntitule(String value) {
        this.intitule = value;
    }

    /**
     * Gets the value of the thematique property.
     * 
     * @return
     *     possible object is
     *     {@link ThematiqueEpi }
     *     
     */
    public ThematiqueEpi getThematique() {
        return thematique;
    }

    /**
     * Sets the value of the thematique property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThematiqueEpi }
     *     
     */
    public void setThematique(ThematiqueEpi value) {
        this.thematique = value;
    }

    /**
     * Gets the value of the disciplineRefs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the disciplineRefs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisciplineRefs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getDisciplineRefs() {
        if (disciplineRefs == null) {
            disciplineRefs = new ArrayList<Object>();
        }
        return this.disciplineRefs;
    }

}
