//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.util.ArrayList;
import java.util.List;


/**
 * Contient l'intitul�, le commentaire et les couples
 *             enseignant/discipline d'un EPI d�fini pour un groupe d'�l�ves
 *             
 * 
 * <p>Java class for EpiGroupe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EpiGroupe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="commentaire" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine600" minOccurs="0"/>
 *         &lt;element name="enseignants-disciplines">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="enseignant-discipline" type="{urn:fr:edu:scolarite:lsun:bilans:import}EnseignantDiscipline"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="epi-ref" use="required" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *       &lt;attribute name="intitule" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine150" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EpiGroupe", propOrder = {
    "commentaire",
    "enseignantsDisciplines"
})
public class EpiGroupe {

    protected String commentaire;
    @XmlElement(name = "enseignants-disciplines", required = true)
    protected EnseignantsDisciplines enseignantsDisciplines;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "epi-ref", required = true)
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object epiRef;
    @XmlAttribute(name = "intitule", required = true)
    protected String intitule;

    /**
     * Gets the value of the commentaire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommentaire() {
        return commentaire;
    }

    /**
     * Sets the value of the commentaire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommentaire(String value) {
        this.commentaire = value;
    }

    /**
     * Gets the value of the enseignantsDisciplines property.
     * 
     * @return
     *     possible object is
     *     {@link EnseignantsDisciplines }
     *     
     */
    public EnseignantsDisciplines getEnseignantsDisciplines() {
        return enseignantsDisciplines;
    }

    /**
     * Sets the value of the enseignantsDisciplines property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnseignantsDisciplines }
     *     
     */
    public void setEnseignantsDisciplines(EnseignantsDisciplines value) {
        this.enseignantsDisciplines = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the epiRef property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getEpiRef() {
        return epiRef;
    }

    /**
     * Sets the value of the epiRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setEpiRef(Object value) {
        this.epiRef = value;
    }

    /**
     * Gets the value of the intitule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntitule() {
        return intitule;
    }

    /**
     * Sets the value of the intitule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntitule(String value) {
        this.intitule = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="enseignant-discipline" type="{urn:fr:edu:scolarite:lsun:bilans:import}EnseignantDiscipline"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enseignantDiscipline"
    })
    public static class EnseignantsDisciplines {

        @XmlElement(name = "enseignant-discipline", required = true)
        protected List<EnseignantDiscipline> enseignantDiscipline;

        /**
         * Gets the value of the enseignantDiscipline property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the enseignantDiscipline property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEnseignantDiscipline().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link EnseignantDiscipline }
         * 
         * 
         */
        public List<EnseignantDiscipline> getEnseignantDiscipline() {
            if (enseignantDiscipline == null) {
                enseignantDiscipline = new ArrayList<EnseignantDiscipline>();
            }
            return this.enseignantDiscipline;
        }

    }

}
