/*
 * Copyright (c) Région Hauts-de-France, Département de la Seine-et-Marne, CGI, 2016.
 *     This file is part of OPEN ENT NG. OPEN ENT NG is a versatile ENT Project based on the JVM and ENT Core Project.
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as
 *   published by the Free Software Foundation (version 3 of the License).
 *   For the sake of explanation, any module that communicate over native
 *   Web protocols, such as HTTP, with OPEN ENT NG is outside the scope of this
 *   license and could be license under its own terms. This is merely considered
 *   normal use of OPEN ENT NG, and does not fall under the heading of "covered work".
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;


/**
 * D�crit la structure de l'�l�ment racine du document
 *             
 * 
 * <p>Java class for LsunBilans complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LsunBilans">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entete" type="{urn:fr:edu:scolarite:lsun:bilans:import}Entete"/>
 *         &lt;element name="donnees" type="{urn:fr:edu:scolarite:lsun:bilans:import}Donnees"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaVersion" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="2.0"/>
 *             &lt;enumeration value="3.0"/>
 *             &lt;enumeration value="4.0"/>
 *             &lt;enumeration value="5.0"/>
 *             &lt;enumeration value="6.0"/>
 *             &lt;enumeration value="7.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LsunBilans", propOrder = {
    "entete",
    "donnees"
})
@XmlRootElement(name="lsun-bilans")
public class LsunBilans {

    @XmlElement(required = true)
    protected Entete entete;
    @XmlElement(required = true)
    protected Donnees donnees;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the entete property.
     * 
     * @return
     *     possible object is
     *     {@link Entete }
     *     
     */
    public Entete getEntete() {
        return entete;
    }

    /**
     * Sets the value of the entete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entete }
     *     
     */
    public void setEntete(Entete value) {
        this.entete = value;
    }

    /**
     * Gets the value of the donnees property.
     * 
     * @return
     *     possible object is
     *     {@link Donnees }
     *     
     */
    public Donnees getDonnees() {
        return donnees;
    }

    /**
     * Sets the value of the donnees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Donnees }
     *     
     */
    public void setDonnees(Donnees value) {
        this.donnees = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
