//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;


/**
 * D�crit la structure de l'�l�ment racine du document
 *             
 * 
 * <p>Java class for LsunBilans complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LsunBilans">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entete" type="{urn:fr:edu:scolarite:lsun:bilans:import}Entete"/>
 *         &lt;element name="donnees" type="{urn:fr:edu:scolarite:lsun:bilans:import}Donnees"/>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaVersion" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="2.0"/>
 *             &lt;enumeration value="3.0"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LsunBilans", propOrder = {
    "entete",
    "donnees"
})
@XmlRootElement(name="lsun-bilans")
public class LsunBilans {

    @XmlElement(required = true)
    protected Entete entete;
    @XmlElement(required = true)
    protected Donnees donnees;
    @XmlAttribute(name = "schemaVersion", required = true)
    protected String schemaVersion;

    /**
     * Gets the value of the entete property.
     * 
     * @return
     *     possible object is
     *     {@link Entete }
     *     
     */
    public Entete getEntete() {
        return entete;
    }

    /**
     * Sets the value of the entete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Entete }
     *     
     */
    public void setEntete(Entete value) {
        this.entete = value;
    }

    /**
     * Gets the value of the donnees property.
     * 
     * @return
     *     possible object is
     *     {@link Donnees }
     *     
     */
    public Donnees getDonnees() {
        return donnees;
    }

    /**
     * Sets the value of the donnees property.
     * 
     * @param value
     *     allowed object is
     *     {@link Donnees }
     *     
     */
    public void setDonnees(Donnees value) {
        this.donnees = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

}
