//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;


/**
 * Contient les parcours �ducatifs d'un �l�ve 
 * 
 * <p>Java class for ModaliteAccompagnement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModaliteAccompagnement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="complement-ppre" type="{urn:fr:edu:scolarite:lsun:bilans:import}Chaine600" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="code" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}CodeModalite" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModaliteAccompagnement", propOrder = {
    "complementPpre"
})
public class ModaliteAccompagnement {

    @XmlElement(name = "complement-ppre")
    protected String complementPpre;
    @XmlAttribute(name = "code", required = true)
    protected CodeModalite code;

    /**
     * Gets the value of the complementPpre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComplementPpre() {
        return complementPpre;
    }

    /**
     * Sets the value of the complementPpre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComplementPpre(String value) {
        this.complementPpre = value;
    }

    /**
     * Gets the value of the code property.
     * 
     * @return
     *     possible object is
     *     {@link CodeModalite }
     *     
     */
    public CodeModalite getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeModalite }
     *     
     */
    public void setCode(CodeModalite value) {
        this.code = value;
    }

}
