//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import org.vertx.java.core.json.JsonArray;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.edu.scolarite.lsun.bilans._import package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LsunBilans_QNAME = new QName("urn:fr:edu:scolarite:lsun:bilans:import", "lsun-bilans");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.edu.scolarite.lsun.bilans._import
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccPersoGroupe }
     * 
     */
    public AccPersoGroupe createAccPersoGroupe() {
        return new AccPersoGroupe();
    }

    /**
     * Create an instance of {@link Donnees }
     * 
     */
    public Donnees createDonnees() {
        return new Donnees();
    }

    /**
     * Create an instance of {@link Donnees.ParcoursCommuns }
     * 
     */
    public Donnees.ParcoursCommuns createDonneesParcoursCommuns() {
        return new Donnees.ParcoursCommuns();
    }

    /**
     * Create an instance of {@link BilanPeriodique }
     * 
     */
    public BilanPeriodique createBilanPeriodique() {
        return new BilanPeriodique();
    }

    /**
     * Create an instance of {@link BilanCycle }
     * 
     */
    public BilanCycle createBilanCycle() {
        return new BilanCycle();
    }

    /**
     * Create an instance of {@link EpiGroupe }
     * 
     */
    public EpiGroupe createEpiGroupe() {
        return new EpiGroupe();
    }

    /**
     * Create an instance of {@link LsunBilans }
     * 
     */
    public LsunBilans createLsunBilans() {
        return new LsunBilans();
    }

    /**
     * Create an instance of {@link VieScolaire }
     * 
     */
    public VieScolaire createVieScolaire() {
        return new VieScolaire();
    }

    /**
     * Create an instance of {@link ElementProgramme }
     * 
     */
    public ElementProgramme createElementProgramme() {
        return new ElementProgramme();
    }

    /**
     * Create an instance of {@link DomaineSocle }
     * 
     */
    public DomaineSocle createDomaineSocle() {
        return new DomaineSocle();
    }

    /**
     * Create an instance of {@link Periode }
     * 
     */
    public Periode createPeriode() {
        return new Periode();
    }

    /**
     * Create an instance of {@link Enseignant }
     * 
     */
    public Enseignant createEnseignant() {
        return new Enseignant();
    }

    /**
     * Create an instance of {@link VieScolaireCommun }
     * 
     */
    public VieScolaireCommun createVieScolaireCommun() {
        return new VieScolaireCommun();
    }

    /**
     * Create an instance of {@link Parcours }
     * 
     */
    public Parcours createParcours() {
        return new Parcours();
    }

    /**
     * Create an instance of {@link Epi }
     * 
     */
    public Epi createEpi() {
        return new Epi();
    }

    /**
     * Create an instance of {@link ModaliteAccompagnement }
     * 
     */
    public ModaliteAccompagnement createModaliteAccompagnement() {
        return new ModaliteAccompagnement();
    }

    /**
     * Create an instance of {@link AccPersoEleve }
     * 
     */
    public AccPersoEleve createAccPersoEleve() {
        return new AccPersoEleve();
    }

    /**
     * Create an instance of {@link Discipline }
     * 
     */
    public Discipline createDiscipline() {
        return new Discipline();
    }

    /**
     * Create an instance of {@link DomaineSocleCycle }
     * 
     */
    public DomaineSocleCycle createDomaineSocleCycle() {
        return new DomaineSocleCycle();
    }
    public DomaineSocleCycle createDomaineSocleCycle(String code, Integer positionnement){
        return new DomaineSocleCycle(code,positionnement);
    }
    /**
     * Create an instance of {@link EnseignementComplement }
     * 
     */
    public EnseignementComplement createEnseignementComplement() {
        return new EnseignementComplement();
    }
    public EnseignementComplement createEnseignementComplement(String code, Integer niveau){
        return new EnseignementComplement(code, niveau );
    }

    /**
     * Create an instance of {@link EpiEleve }
     * 
     */
    public EpiEleve createEpiEleve() {
        return new EpiEleve();
    }

    /**
     * Create an instance of {@link Responsable }
     * 
     */
    public Responsable createResponsable() {
        return new Responsable();
    }
    /*Attention pour la civilité il faudra tenir compte de la class enum Civilte*/
    public Responsable createResponsable(String externalId, Civilite civilite, String nom, String prenom, String relative, Adresse adresse){
        return new Responsable( externalId, civilite, nom,  prenom, relative,adresse);
    }
    public Responsable createResponsable(String externalId, String nom, String prenom, String relative, Adresse adresse){
        return new Responsable( externalId, nom, prenom, relative, adresse );
    }
    public Responsable createResponsable(String externalId, String nom, String prenom, String relative){
        return new Responsable( externalId, nom,  prenom, relative);
    }

    /**
     * Create an instance of {@link Eleve }
     * 
     */
    public Eleve createEleve() {
        return new Eleve();
    }
    public Eleve createEleve(String externalId,String attachementId,String firstName, String lastName, String nameClass, String idNeo4j,String idClass,String level){
        return new Eleve( externalId, attachementId, firstName, lastName,  nameClass,  idNeo4j, idClass,level);
    }
    /**
     * Create an instance of {@link AccPerso }
     * 
     */
    public AccPerso createAccPerso() {
        return new AccPerso();
    }

    /**
     * Create an instance of {@link ResponsableEtab }
     * 
     */
    public ResponsableEtab createResponsableEtab() {
        return new ResponsableEtab();
    }
    public ResponsableEtab createResponsableEtab(String externalId,String displayName){
        return new ResponsableEtab(externalId,displayName);
    }
    /**
     * Create an instance of {@link Adresse }
     * 
     */
    public Adresse createAdresse() {
        return new Adresse();
    }
    public Adresse createAdresse(String ligne1,String codePostal, String commune){
        return new Adresse( ligne1, codePostal, commune);
    }

    /**
     * Create an instance of {@link EnseignantDiscipline }
     * 
     */
    public EnseignantDiscipline createEnseignantDiscipline() {
        return new EnseignantDiscipline();
    }

    /**
     * Create an instance of {@link Entete }
     * 
     */
    public Entete createEntete(String editeur, String application, String etablissement) {
        return new Entete(editeur, application, etablissement);
    }
   /*public Entete Entete() {
        return new Entete();
    }*/
    /**
     * Create an instance of {@link Acquis }
     * 
     */
    public Acquis createAcquis() {
        return new Acquis();
    }

    /**
     * Create an instance of {@link AccPersoGroupe.EnseignantsDisciplines }
     * 
     */
    public AccPersoGroupe.EnseignantsDisciplines createAccPersoGroupeEnseignantsDisciplines() {
        return new AccPersoGroupe.EnseignantsDisciplines();
    }

    /**
     * Create an instance of {@link Donnees.ResponsablesEtab }
     * 
     */
    public Donnees.ResponsablesEtab createDonneesResponsablesEtab() {
        return new Donnees.ResponsablesEtab();
    }

    /**
     * Create an instance of {@link Donnees.Eleves }
     * 
     */
    public Donnees.Eleves createDonneesEleves() {
        return new Donnees.Eleves();
    }

    /**
     * Create an instance of {@link Donnees.Periodes }
     * 
     */
    public Donnees.Periodes createDonneesPeriodes() {
        return new Donnees.Periodes();
    }

    /**
     * Create an instance of {@link Donnees.Disciplines }
     * 
     */
    public Donnees.Disciplines createDonneesDisciplines() {
        return new Donnees.Disciplines();
    }

    /**
     * Create an instance of {@link Donnees.Enseignants }
     * 
     */
    public Donnees.Enseignants createDonneesEnseignants() {
        return new Donnees.Enseignants();
    }

    /**
     * Create an instance of {@link Donnees.ElementsProgramme }
     * 
     */
    public Donnees.ElementsProgramme createDonneesElementsProgramme() {
        return new Donnees.ElementsProgramme();
    }

    /**
     * Create an instance of {@link Donnees.ViesScolairesCommuns }
     * 
     */
    public Donnees.ViesScolairesCommuns createDonneesViesScolairesCommuns() {
        return new Donnees.ViesScolairesCommuns();
    }

    /**
     * Create an instance of {@link Donnees.Epis }
     * 
     */
    public Donnees.Epis createDonneesEpis() {
        return new Donnees.Epis();
    }

    /**
     * Create an instance of {@link Donnees.EpisGroupes }
     * 
     */
    public Donnees.EpisGroupes createDonneesEpisGroupes() {
        return new Donnees.EpisGroupes();
    }

    /**
     * Create an instance of {@link Donnees.AccPersos }
     * 
     */
    public Donnees.AccPersos createDonneesAccPersos() {
        return new Donnees.AccPersos();
    }

    /**
     * Create an instance of {@link Donnees.AccPersosGroupes }
     * 
     */
    public Donnees.AccPersosGroupes createDonneesAccPersosGroupes() {
        return new Donnees.AccPersosGroupes();
    }

    /**
     * Create an instance of {@link Donnees.BilansPeriodiques }
     * 
     */
    public Donnees.BilansPeriodiques createDonneesBilansPeriodiques() {
        return new Donnees.BilansPeriodiques();
    }

    /**
     * Create an instance of {@link Donnees.BilansCycle }
     * 
     */
    public Donnees.BilansCycle createDonneesBilansCycle() {
        return new Donnees.BilansCycle();
    }

    /**
     * Create an instance of {@link Donnees.ParcoursCommuns.ParcoursCommun }
     * 
     */
    public Donnees.ParcoursCommuns.ParcoursCommun createDonneesParcoursCommunsParcoursCommun() {
        return new Donnees.ParcoursCommuns.ParcoursCommun();
    }

    /**
     * Create an instance of {@link BilanPeriodique.ListeAcquis }
     * 
     */
    public BilanPeriodique.ListeAcquis createBilanPeriodiqueListeAcquis() {
        return new BilanPeriodique.ListeAcquis();
    }

    /**
     * Create an instance of {@link BilanPeriodique.EpisEleve }
     * 
     */
    public BilanPeriodique.EpisEleve createBilanPeriodiqueEpisEleve() {
        return new BilanPeriodique.EpisEleve();
    }

    /**
     * Create an instance of {@link BilanPeriodique.AccPersosEleve }
     * 
     */
    public BilanPeriodique.AccPersosEleve createBilanPeriodiqueAccPersosEleve() {
        return new BilanPeriodique.AccPersosEleve();
    }

    /**
     * Create an instance of {@link BilanPeriodique.ListeParcours }
     * 
     */
    public BilanPeriodique.ListeParcours createBilanPeriodiqueListeParcours() {
        return new BilanPeriodique.ListeParcours();
    }

    /**
     * Create an instance of {@link BilanPeriodique.ModalitesAccompagnement }
     * 
     */
    public BilanPeriodique.ModalitesAccompagnement createBilanPeriodiqueModalitesAccompagnement() {
        return new BilanPeriodique.ModalitesAccompagnement();
    }

    /**
     * Create an instance of {@link BilanPeriodique.Socle }
     * 
     */
    public BilanPeriodique.Socle createBilanPeriodiqueSocle() {
        return new BilanPeriodique.Socle();
    }

    /**
     * Create an instance of {@link BilanPeriodique.Responsables }
     * 
     */
    public BilanPeriodique.Responsables createBilanPeriodiqueResponsables() {
        return new BilanPeriodique.Responsables();
    }

    /**
     * Create an instance of {@link BilanCycle.Socle }
     * 
     */
    public BilanCycle.Socle createBilanCycleSocle() {
        return new BilanCycle.Socle();
    }

    /**
     * Create an instance of {@link BilanCycle.Responsables }
     * 
     */
    public BilanCycle.Responsables createBilanCycleResponsables() {
        return new BilanCycle.Responsables();
    }

    /**
     * Create an instance of {@link EpiGroupe.EnseignantsDisciplines }
     * 
     */
    public EpiGroupe.EnseignantsDisciplines createEpiGroupeEnseignantsDisciplines() {
        return new EpiGroupe.EnseignantsDisciplines();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LsunBilans }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:fr:edu:scolarite:lsun:bilans:import", name = "lsun-bilans")
    public JAXBElement<LsunBilans> createLsunBilans(LsunBilans value) {
        return new JAXBElement<LsunBilans>(_LsunBilans_QNAME, LsunBilans.class, null, value);
    }

}
