//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:fr:edu:scolarite:lsun:bilans:import", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.openent.competences.bean.lsun;
