//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * D�crit une p�riode p�dagogique (trimestre, semestre ou autre) avec
 *                 son indice et le nombre de p�riodes composant l'ann�e scolaire
 *             
 * 
 * <p>Java class for Periode complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Periode">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="millesime" use="required" type="{urn:fr:edu:scolarite:lsun:bilans:import}Millesime" />
 *       &lt;attribute name="indice" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="nb-periodes" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Periode")
public class Periode {

    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "millesime", required = true)
    protected String millesime;
    @XmlAttribute(name = "indice", required = true)
    protected int indice;
    @XmlAttribute(name = "nb-periodes", required = true)
    protected int nbPeriodes;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the millesime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMillesime() {
        return millesime;
    }

    /**
     * Sets the value of the millesime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMillesime(String value) {
        this.millesime = value;
    }

    /**
     * Gets the value of the indice property.
     * 
     */
    public int getIndice() {
        return indice;
    }

    /**
     * Sets the value of the indice property.
     * 
     */
    public void setIndice(int value) {
        this.indice = value;
    }

    /**
     * Gets the value of the nbPeriodes property.
     * 
     */
    public int getNbPeriodes() {
        return nbPeriodes;
    }

    /**
     * Sets the value of the nbPeriodes property.
     * 
     */
    public void setNbPeriodes(int value) {
        this.nbPeriodes = value;
    }

}
