//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.06 at 05:11:16 PM CEST 
//


package fr.openent.competences.bean.lsun;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThematiqueEpi.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ThematiqueEpi">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EPI_SAN"/>
 *     &lt;enumeration value="EPI_ART"/>
 *     &lt;enumeration value="EPI_EDD"/>
 *     &lt;enumeration value="EPI_ICC"/>
 *     &lt;enumeration value="EPI_LGA"/>
 *     &lt;enumeration value="EPI_LGE"/>
 *     &lt;enumeration value="EPI_PRO"/>
 *     &lt;enumeration value="EPI_STS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ThematiqueEpi")
@XmlEnum
public enum ThematiqueEpi {

    EPI_SAN,
    EPI_ART,
    EPI_EDD,
    EPI_ICC,
    EPI_LGA,
    EPI_LGE,
    EPI_PRO,
    EPI_STS;

    public String value() {
        return name();
    }

    public static ThematiqueEpi fromValue(String v) {
        return valueOf(v);
    }

}
