export enum ReportModelPrintExportConstant {
    COLLECTION_REPORT_MODEL = "report_model",
    KEY_ID = "_id",
    KEY_USER_ID = "userId",
    KEY_STRUCTUREID = "structureId",
    KEY_TITLE = "title",
    KEY_SELECTED = "selected",
    KEY_PREFERENCES_CHECKBOX = "preferencesCheckbox",
    KEY_PREFERENCES_TEXT = "preferencesText",
    STATUS = "status",
    URL_API_POST = "/competences/report-model-print-export",
    URL_API_GET_ALL = "/competences/reports-models-print-export/structure/",
    URL_API_PUT = "/competences/report-model-print-export/",
    URL_API_GET_SELECTED = "/competences/reports-models-print-export/selected",
    URL_API_GET_ONE = "/competences/reports-models-print-export/",
    URL_API_DELETE = "/competences/report-model-print-export/",
    DELETED = "deleted",
    PUTED = "puted",
    POSTED = "posted",
}

export enum ReportsModelsPrintExportPreferencesCheckboxConst {
    CLASS_AVERAGE  = "moyenneClasse",
    GENERAL_AVEREGE = "moyenneGenerale",
    GET_PROGRAM_ELEMENTS = "getProgramElements",
    GET_RESPONSABLE = "getResponsable",
    COEFFICIENT = "coefficient",
    CLASS_AVERAGE_MIN_MAX = "classAverageMinMax",
    STUDENT_AVERAGE = "moyenneEleve",
    SHOW_BILAN_PER_DOMAIN = "showBilanPerDomaines",
    SHOW_PROJECTS = "showProjects",
    CLASS_AVERAGE_UNDER_SUBJECT = "moyenneClasseSousMat",
    ANNUAL_AVERAGE = "moyenneAnnuelle",
    WITH_LEVELS_STUDENT = "withlevelsStudent",
    SHOW_FAMILY = "showFamily",
    WITH_LEVELS_CLASS = "withLevelsClass",
    POSITIONING = "positionnement",
    STUDENT_RANK = "studentRank",
    USE_MODEL = "useModel",
    AGRICULTURE_LOGO = "agricultureLogo",
    STUDENT_AVERAGE_UNDER_SUBJECT = "moyenneEleveSousMat",
    POSITIONING_UNDER_SUBJECT = "positionnementSousMat",
    ADD_OTHER_TEACHER = "addOtherTeacher",
    HIDE_HEAD_TEACHER = "hideHeadTeacher",
    SIMPLE = "simple",
    NEUTRAL = "neutre",
}

export enum ReportsModelsPrintExportPreferencesTextConst {
    MENTION_OPINION = "mentionOpinion",
    ORIENTATION_OPINION = "orientationOpinion",
    NAME_CE = "nameCE",
    IMG_STRUCTURE = "imgStructure",
    IMG_SIGNATURE = "imgSignature",
    OTHER_TEACHER_ID = "otherTeacherId",
    OTHER_TEACHER_NAME = "otherTeacherName",
    FUNCTION_OTHER_TEACHER = "functionOtherTeacher",
    ID_MODEL = "idModel",
    MENTION_CLASS = "mentionClass",
}